services:
  admin-panel:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_AUTH_KEY=${VITE_AUTH_KEY}
    container_name: admin-panel
    restart: always
    ports:
      - 7778:80
